### ISSUE TITLE
TRG 4.03 image has `USER` command and Non Root Container

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/ssi-credential-issuer#135]
Missing User cmd 

`RUN chown -R 1000:3000 /app`

Link to example: https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03#implementation
#Pull the base image as Ubuntu
FROM ubuntu:latest

#Add a user with userid 1000 and name nonroot
RUN useradd −u 1000 nonroot

#Run Container as nonroot
USER nonroot

Hint securityContext User reference to `1000` in your example:
https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/fd8e687fa2ef80b2fef5b83206a7e4c206d7acf6/charts/ssi-credential-issuer/templates/job-issuer-migrations.yaml#L36
    
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  securityContext:
    runAsUser: 1000 # SPECIFY USER ID HERE
  containers:
  - name: example-container
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      allowPrivilegeEscalation: false # SET THIS TO FALSE
```
