### ISSUE TITLE
Helm not fetching the correct postgres password

### ISSUE THREAD

**Issue by kss682** [eclipse-tractusx/ssi-credential-issuer#373]
We have configured the yaml the following way.
```
  postgresql:
    enabled: true
    architecture: standalone
    primary:
      persistence:
        enabled: false
    auth:
      # -- Password for the root username 'postgres'. Secret-key 'postgres-password'.
      username: "issuer"
      postgrespassword: "<>
      # -- Password for the non-root username 'issuer'. Secret-key 'password'.
      password: "<>"
```
But the migration worker fails to connect and hence the db is not populated.
```
  Exception data:
    Severity: FATAL
    SqlState: 28P01
    MessageText: password authentication failed for user "issuer"
    File: auth.c
    Line: 326
    Routine: auth_failed
```
Meanwhile, I'm able to manually login using the same credentials. 

![Image](https://github.com/user-attachments/assets/ca202c67-b02a-4151-aded-e163844253df)

Secrets are present 
![Image](https://github.com/user-attachments/assets/958d2e69-3136-44c0-845a-5afc22772dfe)

But the migration job fails to connect. 

Could you please help in understanding what we might have missed ?
